name: Build Kernel Module

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git

    - name: Clone Kernel Source
      run: |
        # Clone the kernel source
        git clone https://android.googlesource.com/kernel/oplus/linux.git
        cd linux
        git checkout <branch_name>  # Checkout the appropriate branch

    - name: Build Kernel Module
      run: |
        cd ksu_kernel_oplus_RMX3461  # Navigate to your kernel module directory
        make -C ../linux M=$(PWD) modules  # Adjust the path if necessary

    - name: Upload Kernel Module
      uses: actions/upload-artifact@v2
      with:
        name: ksu_kernel_oplus_RMX3461
        path: ksu_kernel_oplus_RMX3461/*.ko  # Adjust the pattern if different
