name: Build Kernel Module

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git

    - name: Clone Kernel Source
      run: |
        # Update with the correct kernel source repository for your device
        git clone https://github.com/Oppo/kernel_oplus.git  # Example URL
        cd kernel_oplus
        git checkout <branch_name>  # Replace with the correct branch name

    - name: Build Kernel Module
      run: |
        cd ksu_kernel_oplus_RMX3461  # Navigate to your kernel module directory
        make -C ../kernel_oplus M=$(PWD) modules  # Adjust the path if necessary

    - name: Upload Kernel Module
      uses: actions/upload-artifact@v3
      with:
        name: ksu_kernel_oplus_RMX3461
        path: ksu_kernel_oplus_RMX3461/*.ko  # Adjust the pattern if different
